Dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),                      # 富文本编辑器
    path('search/', include('haystack.urls')),                      # 全文检索框架

    path('user/', include('user.urls', namespace="user")),          # 用户模块
    path('cart/', include("cart.urls", namespace='cart')),          # 购物车模块
    path('order/', include("order.urls", namespace='order')),       # 订单模块
    path('goods/', include("goods.urls", namespace='goods')),       # 商品模块
]


# pip install Pillow

apps/goods/urls.py
from django.urls import path,re_path
from apps.goods.views import IndexView,DetailView,ListView
# from apps.goods.search_views import MySeachView

app_name = 'apps.goods'

urlpatterns = [
    path('index', IndexView.as_view(), name='index'),
    re_path('^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),
    re_path('^goods/list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),
    # re_path('^goods/(?P<goods_id>\d+)$', MySeachView.as_view(), name='seachview'),
]

apps/user/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, UserSiteView, LogoutView

# app_name = 'apps.user'      # 是否注释待定
app_name = 'user'      # 是否注释待定

urlpatterns = [
    # path('register/', register, name='register'),                        # 注册
    # path('register_handle', register_handle, name='register_handle'),    # 注册处理

    path('register', RegisterView.as_view(), name='register'),             # 注册
    re_path('active/(?P<token>.*)', ActiveView.as_view(), name='active'),  # 用户激活
    path('login', LoginView.as_view(), name='login'),                      # 登录
    path('logout', LogoutView.as_view(), name='logout'),                   # 退出登录

    # 方案1：使用 login_required()
    # path('', login_required(UserInfoView.as_view()), name='user'),               # 用户信息
    # path('order/', login_required(UserOrderView.as_view()), name='order'),       # 订单
    # path('address/', login_required(UserSiteView.as_view()), name='address'),    # 地址

    # 方案2：使用LoginRequiredMixin装饰器
    path('', UserInfoView.as_view(), name='user'),                               # 用户信息
    re_path('^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),     # 订单
    path('address/', UserSiteView.as_view(), name='address'),                    # 地址

]

templates/df_order/order_comment.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-订单评价</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<form action="/search"  method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" >· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" >· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" >· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">订单评价</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status_name }}</li>
				</ul>
                <form method="post">
				    {% csrf_token %}
                    <input type="hidden" name="order_id" value="{{ order.order_id }}"/>
                    <input type="hidden" name="total_count" value="{{ order.total_count }}"/>
                    {% for order_sku in order.order_skus %}
                        <table class="order_list_table w980">
                            <tbody>
                                <tr>
                                    <td width="55%">
                                        <ul class="order_goods_list clearfix">
                                            <li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
                                            <li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>
                                            <li class="col03">{{ order_sku.count }}</li>

                                        </ul>
                                    </td>
                                    <td width="20%">{{ order_sku.amount }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="site_con">
                            <input type="hidden" name="sku_{{ forloop.counter }}" value="{{ order_sku.sku_id }}"/>
                            <div class="form_group form_group2">
                                <label>评价内容：</label>
                                <textarea  class="site_area" name="content_{{ forloop.counter }}"></textarea>
                            </div>
                        </div>
                    {% endfor %}
                    <input type="submit" value="提交" class="info_submit"/>
                </form>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>

templates/df_order/pay.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Pay</title>
  </head>
  <body>
    订单编号：{{oid}}
    订单状态:已支付
    <script>
     setTimeout('location.href="/user/user_center_order&1/";',3000);
    </script>
  </body>
</html>

templates/df_order/place_order.html
{% extends 'base.html' %}
{% block head %}
<script>
 $(function(){
   /* 计算价格小计与总计，并加上运费*/
   var priceTotal = 0
   var priceSum = 0
   $('.goods_list_td').each(function(){
     count = parseInt($(this).children('.col06').text());
     price = parseFloat($(this).children('.col05').text());
     priceTotal = count*price;
     $(this).children('.col07').text(priceTotal.toFixed(2));
     priceSum += priceTotal
   });
   $('#gcount').text($('.goods_list_td').length);
   $('#sumtotal').text(priceSum+'元');
   totalPay = priceSum + 10;
   $('#total_pay').text(totalPay+'元');

   /* 下订单触发click事件，用来校验订单是否下成功，根据AJAX返回值展示不同页面*/
   $('#order_btn').click(function(){
     orderid = []
     $('.goods_list_td').each(function(){
       orderid.push($(this).attr('id'));
     });

     localStorage.setItem('order_finish',2);

     $.post({
       url:'/order/addorder/',
       dataType:'json',
       type:'POST',
       data:{
         'csrfmiddlewaretoken': '{{ csrf_token }}',
         id:orderid,
         total:totalPay,
         address:$('#oaddress').text(),
       },
     })
      .done(function(data){
        if(data.status == 1){
          $('.popup_con p').text('订单提交成功！');
          $('.popup_con').fadeIn('fast', function() {
            setTimeout(function(){
              $('.popup_con').fadeOut('fast',function(){
	        window.location.href = '/user/user_center_order&1/';
              });
            },3000)
          });
        }
        else if(data.status == 2){
          $('.popup_con p').text('超出库存请修改！');
          $('.popup_con').fadeIn('fast', function() {
            setTimeout(function(){
              $('.popup_con').fadeOut('fast',function(){
	        window.location.href = '/cart/';
              });
            },3000)
          });
        }
      });

   });

 })
</script>

{% endblock head %}
{% block body %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">{{user.uaddress}} （{{user.ushou}} 收） {{user.uphone}}</dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		{%for order in orderlist %}
		<ul class="goods_list_td clearfix" id="{{order.id}}">
			<li class="col01">{{order.id}}</li>
			<li class="col02"><img src="/static/{{order.goods.gpic}}"></li>
			<li class="col03">{{order.goods.gtitle}}</li>
			<li class="col04">{{order.goods.gunit}}</li>
			<li class="col05">{{order.goods.gprice}}</li>
			<li class="col06">{{order.count}}</li>
			<li class="col07">{{order.goods.gprice}}</li>
		</ul>
		{%endfor%}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em id="gcount">2</em>件商品，总金额<b id="sumtotal">42.60元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b id="total_pay">52.60元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>

<div class="popup_con">
  <div class="popup">
    <p></p>
  </div>

  <div class="mask"></div>
</div>
{% endblock body %}